### ISSUE TITLE
Pentair IntelliChlor packets

### ISSUE THREAD

**Issue by hartmms** [dminear/easy-touch-raspberry-pi#1]
Sorry for filing an "issue" - it's really more of a "request for information"....

Do you happen to have an IntelliChlor in your setup?  I'm looking for data on how to control it via RS485.  Not much info seems to be available online for this.  I have a friend that has a complete Pentair system, so I might have to go install a packet sniffer to get some data to decode if not. 

I too have a home brew controller, but my brain is a Synapse wireless module. I have it control my pump, read a PH and ORP sensor, and control my LED light. The module talks to a webgateway running websockets written in the python Tornado web app. I would like to add capability to control the IntelliChlor IC40 I'm about to get.  I only have a 15k gallon pool, but will get the IC40 that's meant for 40k gallon pools so the cell will last longer. The default 20% or 40% manual settings might be too coarse for my needs.

**Comment by dminear** [comment]
Yes I do, but I think I broke control of it. I will try to get it working. In the meantime, you might check out some of the output logs and see if there is anything there. I know I did see an ASCII string "Intellichlor" in the dump.

**Comment by dminear** [comment]
Closing because my IntelliChlor is still broken. The power supply board burned out in the control box.  I think that salinity got too high so it was conducting too much and burned out a diode.  I still have to get around to repairing it, but not sure that will happen. I've been using tablets for the last 2 years and things are working out.
